# Cloudflare Pages configuration
name = "eden-hackathon-frontend"
compatibility_date = "2024-12-01"

# Since we're using static export, we don't need Node.js compatibility
# Remove any server-side functions configuration

[build]
command = "npm run build"
publish = "out"

# Environment variables (if needed)
# [vars]
# NEXT_PUBLIC_API_URL = "your-api-url"
